### ISSUE TITLE
job aws-ecr-credentials-job failed: BackoffLimitExceeded

### ISSUE THREAD

**Issue by RofieSagara** [vaggeliskls/k8s-registry-auth#7]
I try with ecr follow this docs https://github.com/vaggeliskls/k8s-registry-auth/wiki/Examples#aws-ecr-example-existing-secret

but get error while run command 

`helm upgrade --install k8s-registry-auth oci://registry-1.docker.io/vaggeliskls/k8s-registry-auth  --set registry=718981642283.dkr.ecr.ap-southeast-1.amazonaws.com --set awsEcr.enabled=true --set secretConfigName=ecr-secret`

This log that i get it

```
Release "k8s-registry-auth" does not exist. Installing it now.
Pulled: registry-1.docker.io/vaggeliskls/k8s-registry-auth:1.0.3
Digest: sha256:135696b51af9fcc1a67ae76c22ba4af6ebf4b487232b99d85217b937b3c00b5a
Error: failed post-install: 1 error occurred:
	* job aws-ecr-credentials-job failed: BackoffLimitExceeded
```

**Comment by vaggeliskls** [comment]
Hello @RofieSagara 
In Kubernetes, a BackoffLimitExceeded error typically occurs when a Job fails more times than allowed by its backoffLimit (current value is 4). This means that the Job's Pod has repeatedly failed and Kubernetes has stopped retrying.
So try to verify that the secret have the correct AWS ECR credentials
```
apiVersion: v1
kind: Secret
metadata:
  name: global-secret
data:
  REGISTRY_USERNAME: your AWS_ACCESS_KEY in base64 format
  REGISTRY_PASSWORD: your AWS_SECRET_KEY in base64 format
```
